apiVersion: v1
kind: Service
metadata:
  name: helloworld-service   
  labels: 
    app: helloworld-app
    name: helloworld-service
spec: 
  type: LoadBalancer
  ports: 
    - port: 8080
      targetPort: 8080
  selector: 
    app: helloworld-app
    name: helloworld-app-pod
